services:
  cidadaoai_app:
    image: cidadaoai:latest
    command: python -m backend.main
    networks:
      - LomeServer
    environment:
      - CHATWOOT_URL=https://chat.sisgov.app.br
      - CHATWOOT_API_TOKEN=${CHATWOOT_API_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_URL=postgresql://cidadaoai_user:Cid@d@0AI_2024_PG@pgvector:5432/cidadaoai
      - REDIS_URL=redis://chatwoot_chatwoot_redis:6379
    volumes:
      - cidadaoai_media:/app/media
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:
        - traefik.enable=true
        - traefik.http.routers.cidadaoai.rule=Host(`tecnico.sisgov.app.br`)
        - traefik.http.routers.cidadaoai.entrypoints=websecure
        - traefik.http.routers.cidadaoai.tls.certresolver=letsencryptresolver
        - traefik.http.services.cidadaoai.loadbalancer.server.port=8000

networks:
  LomeServer:
    external: true

volumes:
  cidadaoai_media: